all:
   children:
     ubuntusrv:
        hosts:
          target1:
            ansible_host: 10.0.0.7
            ansible_user: knox
            ansible_ssh_private_key_file: ~/.ssh/id_rsa
          target2:
            ansible_host: 10.0.0.8
            ansible_user: knox
            ansible_ssh_private_key_file: ~/.ssh/id_rsa